// Generated by delombok at Sat Sep 17 15:11:19 CEST 2016
/*
Copyright 2011-2015 Stefano Cappa

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
package model;

/**
 * Class with the buffer's size.
 */
public final class BufferSize {
	private static int bufferSize;

	private BufferSize() {
	}

	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public static int getBufferSize() {
		return BufferSize.bufferSize;
	}

	@java.lang.SuppressWarnings("all")
	@javax.annotation.Generated("lombok")
	public static void setBufferSize(final int bufferSize) {
		BufferSize.bufferSize = bufferSize;
	}
}
